apiVersion: v1
kind: Secret
metadata:
    name: private-git
    namespace: bigbang
stringData:
    username: ENC[AES256_GCM,data:3HPvimRp,iv:wotygNn7Ru6UJkqcohf/ooFHfs52MQnRejXhb1qfhDw=,tag:INjMex3AC+Jse8exGzDqEA==,type:str]
    password: ENC[AES256_GCM,data:tOaD5zyyhC1EYaREGUE16FuUMGect3lPT4t10SouSGawQq12HMigjg==,iv:CBSs4ER3VnPyKF4wmRFZW8KGGQhpdMkerYEnk6uKqZA=,tag:pFzG3U6T9p/GFvcW5+fg7A==,type:str]
sops:
    age:
        - recipient: age1am3x4tu2ncv4uj8evt3d7ht0ey999qrp4ezp9jylqwxkjk8h3qrsujn3x4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZktvMHBIT1NYZWE3Sno1
            WGtKeUttbGUzZHUwcXZwNm1CSi9JY016TzFZCkRkUjJhNUZ0K3F2ajZ0RUpiV3pm
            Z2dndmM5VWFxZXV3WnJNejlIdm1tQk0KLS0tIG5kM3czQ3VwaUVhaFQ1Y3hXYlVY
            aEdkWXcza1JaTm0vNGVZZWNmNXMyTmMKxBS4m4mukK11Lh9Tq5H9ARgyPzZ+6SrS
            ZIEEfabBVB5isx06OH9zwDQsqn0jNyYQXRIa+tzhvLSVNGcPGSRzVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-29T20:52:56Z"
    mac: ENC[AES256_GCM,data:C3vzLMWcr0gFMKV4LydJjW6/I3Xz4GohI5qRXqwuT8zdmVEG7irStCuezTFjeVr/XBiP4qQWjQIPkvbuoDPMOaC+AtR0ICPma6d8dinedniIL1EjzlDLowqwITFK7bRfu4CxRxxnkwvj2RpVbvDbJBYAOoNRUDgfgpycsl83cuw=,iv:rDKz9r6eQ8uWPYGwRee1ZkLPkgy829hqmQpwX0tbyrM=,tag:8/zP09GMqmO029Hb4lu+EQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
